/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_macro_name = 1,
  sym_open_paren = 2,
  sym_close_paren = 3,
  sym_identifier = 4,
  anon_sym_u03bb = 5,
  anon_sym_BSLASH = 6,
  anon_sym_DOT = 7,
  sym_comment = 8,
  sym_source_file = 9,
  sym_variable = 10,
  sym_parameter = 11,
  sym_lambda = 12,
  sym_lambda_expression = 13,
  sym_bracketed = 14,
  sym_expression = 15,
  aux_sym_lambda_expression_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_macro_name] = "macro_name",
  [sym_open_paren] = "open_paren",
  [sym_close_paren] = "close_paren",
  [sym_identifier] = "identifier",
  [anon_sym_u03bb] = "\u03bb",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_DOT] = ".",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_variable] = "variable",
  [sym_parameter] = "parameter",
  [sym_lambda] = "lambda",
  [sym_lambda_expression] = "lambda_expression",
  [sym_bracketed] = "bracketed",
  [sym_expression] = "expression",
  [aux_sym_lambda_expression_repeat1] = "lambda_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_macro_name] = sym_macro_name,
  [sym_open_paren] = sym_open_paren,
  [sym_close_paren] = sym_close_paren,
  [sym_identifier] = sym_identifier,
  [anon_sym_u03bb] = anon_sym_u03bb,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_variable] = sym_variable,
  [sym_parameter] = sym_parameter,
  [sym_lambda] = sym_lambda,
  [sym_lambda_expression] = sym_lambda_expression,
  [sym_bracketed] = sym_bracketed,
  [sym_expression] = sym_expression,
  [aux_sym_lambda_expression_repeat1] = aux_sym_lambda_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [sym_open_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_close_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_u03bb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_bracketed] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_lambda_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 6,
  [10] = 4,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 13,
  [19] = 16,
  [20] = 20,
  [21] = 17,
  [22] = 14,
  [23] = 15,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 0x3bb) ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      if (lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '/') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(8);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(8);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_open_paren);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_close_paren);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_u03bb);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_macro_name] = ACTIONS(1),
    [sym_open_paren] = ACTIONS(1),
    [sym_close_paren] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_u03bb] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(28),
    [sym_variable] = STATE(13),
    [sym_lambda_expression] = STATE(13),
    [sym_bracketed] = STATE(13),
    [sym_expression] = STATE(5),
    [sym_macro_name] = ACTIONS(5),
    [sym_open_paren] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_variable] = STATE(18),
    [sym_lambda] = STATE(24),
    [sym_lambda_expression] = STATE(18),
    [sym_bracketed] = STATE(18),
    [sym_expression] = STATE(4),
    [sym_macro_name] = ACTIONS(11),
    [sym_open_paren] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_u03bb] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_variable] = STATE(18),
    [sym_lambda] = STATE(25),
    [sym_lambda_expression] = STATE(18),
    [sym_bracketed] = STATE(18),
    [sym_expression] = STATE(10),
    [sym_macro_name] = ACTIONS(11),
    [sym_open_paren] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_u03bb] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_variable] = STATE(18),
    [sym_lambda_expression] = STATE(18),
    [sym_bracketed] = STATE(18),
    [sym_expression] = STATE(9),
    [sym_macro_name] = ACTIONS(11),
    [sym_open_paren] = ACTIONS(13),
    [sym_close_paren] = ACTIONS(19),
    [sym_identifier] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_variable] = STATE(13),
    [sym_lambda_expression] = STATE(13),
    [sym_bracketed] = STATE(13),
    [sym_expression] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_macro_name] = ACTIONS(5),
    [sym_open_paren] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_variable] = STATE(13),
    [sym_lambda_expression] = STATE(13),
    [sym_bracketed] = STATE(13),
    [sym_expression] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_macro_name] = ACTIONS(25),
    [sym_open_paren] = ACTIONS(23),
    [sym_identifier] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym_variable] = STATE(18),
    [sym_lambda_expression] = STATE(18),
    [sym_bracketed] = STATE(18),
    [sym_expression] = STATE(9),
    [sym_macro_name] = ACTIONS(11),
    [sym_open_paren] = ACTIONS(13),
    [sym_close_paren] = ACTIONS(27),
    [sym_identifier] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym_variable] = STATE(18),
    [sym_lambda_expression] = STATE(18),
    [sym_bracketed] = STATE(18),
    [sym_expression] = STATE(9),
    [sym_macro_name] = ACTIONS(11),
    [sym_open_paren] = ACTIONS(13),
    [sym_close_paren] = ACTIONS(29),
    [sym_identifier] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [sym_variable] = STATE(18),
    [sym_lambda_expression] = STATE(18),
    [sym_bracketed] = STATE(18),
    [sym_expression] = STATE(9),
    [sym_macro_name] = ACTIONS(25),
    [sym_open_paren] = ACTIONS(23),
    [sym_close_paren] = ACTIONS(23),
    [sym_identifier] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [sym_variable] = STATE(18),
    [sym_lambda_expression] = STATE(18),
    [sym_bracketed] = STATE(18),
    [sym_expression] = STATE(9),
    [sym_macro_name] = ACTIONS(11),
    [sym_open_paren] = ACTIONS(13),
    [sym_close_paren] = ACTIONS(31),
    [sym_identifier] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_open_paren,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(8), 1,
      sym_expression,
    STATE(18), 3,
      sym_variable,
      sym_lambda_expression,
      sym_bracketed,
  [21] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_open_paren,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(7), 1,
      sym_expression,
    STATE(18), 3,
      sym_variable,
      sym_lambda_expression,
      sym_bracketed,
  [42] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_macro_name,
    ACTIONS(33), 3,
      ts_builtin_sym_end,
      sym_open_paren,
      sym_identifier,
  [54] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_macro_name,
    ACTIONS(37), 3,
      ts_builtin_sym_end,
      sym_open_paren,
      sym_identifier,
  [66] = 4,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(45), 1,
      sym_comment,
    STATE(20), 2,
      sym_parameter,
      aux_sym_lambda_expression_repeat1,
  [80] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_macro_name,
    ACTIONS(47), 3,
      ts_builtin_sym_end,
      sym_open_paren,
      sym_identifier,
  [92] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      sym_macro_name,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      sym_open_paren,
      sym_identifier,
  [104] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_macro_name,
    ACTIONS(33), 3,
      sym_open_paren,
      sym_close_paren,
      sym_identifier,
  [116] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_macro_name,
    ACTIONS(47), 3,
      sym_open_paren,
      sym_close_paren,
      sym_identifier,
  [128] = 4,
    ACTIONS(45), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_DOT,
    STATE(20), 2,
      sym_parameter,
      aux_sym_lambda_expression_repeat1,
  [142] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      sym_macro_name,
    ACTIONS(51), 3,
      sym_open_paren,
      sym_close_paren,
      sym_identifier,
  [154] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_macro_name,
    ACTIONS(37), 3,
      sym_open_paren,
      sym_close_paren,
      sym_identifier,
  [166] = 4,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_DOT,
    STATE(20), 2,
      sym_parameter,
      aux_sym_lambda_expression_repeat1,
  [180] = 3,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 1,
      sym_comment,
    STATE(15), 2,
      sym_parameter,
      aux_sym_lambda_expression_repeat1,
  [191] = 3,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 1,
      sym_comment,
    STATE(23), 2,
      sym_parameter,
      aux_sym_lambda_expression_repeat1,
  [202] = 2,
    ACTIONS(45), 1,
      sym_comment,
    ACTIONS(62), 2,
      sym_identifier,
      anon_sym_DOT,
  [210] = 2,
    ACTIONS(45), 1,
      sym_comment,
    ACTIONS(64), 1,
      sym_identifier,
  [217] = 2,
    ACTIONS(45), 1,
      sym_comment,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 21,
  [SMALL_STATE(13)] = 42,
  [SMALL_STATE(14)] = 54,
  [SMALL_STATE(15)] = 66,
  [SMALL_STATE(16)] = 80,
  [SMALL_STATE(17)] = 92,
  [SMALL_STATE(18)] = 104,
  [SMALL_STATE(19)] = 116,
  [SMALL_STATE(20)] = 128,
  [SMALL_STATE(21)] = 142,
  [SMALL_STATE(22)] = 154,
  [SMALL_STATE(23)] = 166,
  [SMALL_STATE(24)] = 180,
  [SMALL_STATE(25)] = 191,
  [SMALL_STATE(26)] = 202,
  [SMALL_STATE(27)] = 210,
  [SMALL_STATE(28)] = 217,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracketed, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracketed, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda_expression, 6, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda_expression, 6, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lambda_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lambda_expression_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lambdalus(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lambdalus",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
