/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_macro_name = 1,
  sym_open_paren = 2,
  sym_close_paren = 3,
  sym_variable = 4,
  anon_sym_u03bb = 5,
  anon_sym_BSLASH = 6,
  anon_sym_DOT = 7,
  sym_comment = 8,
  sym_source_file = 9,
  sym_lambda = 10,
  sym_lambda_expression = 11,
  sym_bracketed = 12,
  sym_expression = 13,
  aux_sym_lambda_expression_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_macro_name] = "macro_name",
  [sym_open_paren] = "open_paren",
  [sym_close_paren] = "close_paren",
  [sym_variable] = "variable",
  [anon_sym_u03bb] = "\u03bb",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_DOT] = ".",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_lambda] = "lambda",
  [sym_lambda_expression] = "lambda_expression",
  [sym_bracketed] = "bracketed",
  [sym_expression] = "expression",
  [aux_sym_lambda_expression_repeat1] = "lambda_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_macro_name] = sym_macro_name,
  [sym_open_paren] = sym_open_paren,
  [sym_close_paren] = sym_close_paren,
  [sym_variable] = sym_variable,
  [anon_sym_u03bb] = anon_sym_u03bb,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_lambda] = sym_lambda,
  [sym_lambda_expression] = sym_lambda_expression,
  [sym_bracketed] = sym_bracketed,
  [sym_expression] = sym_expression,
  [aux_sym_lambda_expression_repeat1] = aux_sym_lambda_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [sym_open_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_close_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_u03bb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_bracketed] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_lambda_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_parameter = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_parameter] = "parameter",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_parameter, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(7);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 0x3bb) ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(5);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_macro_name);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_open_paren);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_close_paren);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_variable);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_u03bb);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_macro_name] = ACTIONS(1),
    [sym_open_paren] = ACTIONS(1),
    [sym_close_paren] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [anon_sym_u03bb] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(14),
    [sym_lambda_expression] = STATE(8),
    [sym_bracketed] = STATE(8),
    [sym_expression] = STATE(4),
    [sym_macro_name] = ACTIONS(5),
    [sym_open_paren] = ACTIONS(7),
    [sym_variable] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_lambda] = STATE(13),
    [sym_lambda_expression] = STATE(8),
    [sym_bracketed] = STATE(8),
    [sym_expression] = STATE(5),
    [sym_macro_name] = ACTIONS(5),
    [sym_open_paren] = ACTIONS(7),
    [sym_variable] = ACTIONS(5),
    [anon_sym_u03bb] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_lambda_expression] = STATE(8),
    [sym_bracketed] = STATE(8),
    [sym_expression] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_macro_name] = ACTIONS(11),
    [sym_open_paren] = ACTIONS(11),
    [sym_close_paren] = ACTIONS(11),
    [sym_variable] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_lambda_expression] = STATE(8),
    [sym_bracketed] = STATE(8),
    [sym_expression] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_macro_name] = ACTIONS(5),
    [sym_open_paren] = ACTIONS(7),
    [sym_variable] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_lambda_expression] = STATE(8),
    [sym_bracketed] = STATE(8),
    [sym_expression] = STATE(3),
    [sym_macro_name] = ACTIONS(5),
    [sym_open_paren] = ACTIONS(7),
    [sym_close_paren] = ACTIONS(15),
    [sym_variable] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_lambda_expression] = STATE(8),
    [sym_bracketed] = STATE(8),
    [sym_expression] = STATE(3),
    [sym_macro_name] = ACTIONS(5),
    [sym_open_paren] = ACTIONS(7),
    [sym_close_paren] = ACTIONS(17),
    [sym_variable] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_open_paren,
    STATE(6), 1,
      sym_expression,
    ACTIONS(5), 2,
      sym_macro_name,
      sym_variable,
    STATE(8), 2,
      sym_lambda_expression,
      sym_bracketed,
  [18] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 5,
      ts_builtin_sym_end,
      sym_macro_name,
      sym_open_paren,
      sym_close_paren,
      sym_variable,
  [29] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 5,
      ts_builtin_sym_end,
      sym_macro_name,
      sym_open_paren,
      sym_close_paren,
      sym_variable,
  [40] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 5,
      ts_builtin_sym_end,
      sym_macro_name,
      sym_open_paren,
      sym_close_paren,
      sym_variable,
  [51] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_variable,
    ACTIONS(27), 1,
      anon_sym_DOT,
    STATE(12), 1,
      aux_sym_lambda_expression_repeat1,
  [64] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_variable,
    ACTIONS(32), 1,
      anon_sym_DOT,
    STATE(12), 1,
      aux_sym_lambda_expression_repeat1,
  [77] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 1,
      sym_variable,
    STATE(11), 1,
      aux_sym_lambda_expression_repeat1,
  [87] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
  [94] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      sym_variable,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 18,
  [SMALL_STATE(9)] = 29,
  [SMALL_STATE(10)] = 40,
  [SMALL_STATE(11)] = 51,
  [SMALL_STATE(12)] = 64,
  [SMALL_STATE(13)] = 77,
  [SMALL_STATE(14)] = 87,
  [SMALL_STATE(15)] = 94,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracketed, 3, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda_expression, 6, 0, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lambda_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lambda_expression_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [36] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lambdalus(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lambdalus",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
